language: go

go:
  - "1.x"

cache:
  directories:
    - $GOPATH/pkg/mod

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - GO111MODULE=on

before_install:
  # Install linters and misspell
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin ${GOLANGCI_LINT_VERSION}
  - golangci-lint --version
  # Install Docker image multi-arch builder
  - curl -sfL https://raw.githubusercontent.com/ldez/seihon/master/godownloader.sh | bash -s -- -b "${GOPATH}/bin" ${SEIHON_VERSION}
  - seihon --version

install:
  - go mod tidy
  - git diff --exit-code go.mod
  - git diff --exit-code go.sum
  - go mod download

script:
  - make
  - make image

before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: make publish-images
    on:
      tags: true
